#!/bin/bash
my_list="$*"
#echo "$my_list"
	#Check if the argument is -h or --help
if [[ ${#my_list[@]} == 1 && (($1 == "--help" || $1 == "-h")) ]]; then
	echo "This script takes commands in arguments and tells you wether the commands exist or not and shows you the path."
	echo -e "Usage:\n\t./$(basename $0) commands\n\tor\n\tbash $(basename $0) commands"
    	exit 0
fi
for command in $my_list; do
	#Search the command in the /bin /sbin and /opt folders
	#Some folders where commands are stored are ignored
	#To find the command in the /usr folder needs the root privilege, so it's ignored in that script
	found=$(find /bin/ /sbin/ /opt/ -type f -name "$command")
    	if [ -z $found ]; then
        	echo "${command} is not a command"
    	else
        	echo -e "${command} is a command \tPath: ${found}"
    	fi
done
exit 0

