#!/usr/bin/env bash
# This script displays:
#	FizzBuzz when the number is a multiple of 3 and 5
#	Fizz when the number is multiple of 3
#	Buzz when the number is a multiple of 5
#	Otherwise, the number

for i in {1..100}; do
	if [ $(($i % 3)) -eq 0  -a $(($i % 5)) -eq 0 ]; then
                echo "fizzbuzz"
	elif [[ $(($i % 3)) == 0 ]]; then
		echo "fizz"
	elif [[ $(($i % 5)) == 0 ]]; then
		echo "buzz"
	else
		echo "$i"
	fi
done
