#!/usr/bin/env bash
# This script makes up a story based on /etc/passwd file.
IFS=":"
while read -r username password uid gid GECOS home_directory login_shell; do
	echo "The user ${username} is part of the ${gid} gang, lives in ${home_directory} and rides ${login_shell}. ${uid}'s place is protected by the passcode ${password}, more info about the user here: ${GECOS}"
done < /etc/passwd
