#!/usr/bin/env bash
#This script prints "Best School" and "Hi" at the 9th iteration
i=0
while [ $i -lt 10 ]; do
	if [[ $i == 8 ]]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((i++))
done
