#!/usr/bin/env bash 
# This script displays:
#    	the ith and then "bad luck from China" for the 4th loop iteration
#    	the ith and then "good luck from Japan" for the 9th loop iteration
#    	the ith and then "bad luck from Italy" for the 17th iteration
#	the ith for the others iterations

i=1
while [ $i -le 20 ]; do
	case	$i in
		4)
			echo -e "$i\nbad luck from China"
		;;
		
		9)
			echo "$i\nbad luck from Japan"
		;;
		
		17)
			echo "$i\nbad luck from Italy"
		;;
		
		*)
		echo "$i"
		;;
	esac
	((i++))
done
