#!/usr/bin/env bash 
# This script displays:
#    	the ith and then "bad luck from China" for the 4th loop iteration
#    	the ith and then "good luck from Japan" for the 9th loop iteration
#    	the ith and then "bad luck from Italy" for the 17th iteration
#	the ith for the others iterations

i=1
while [ $i -le 20 ]; do
	if [[ $i == 4 ]]; then
		echo "$i bad luck from China"
	elif [[ $i == 9 ]]; then
		echo "$i bad luck from Japan"
	elif [[ $i == 17 ]]; then
		echo "$i bad luck from Italy"
	else
		echo "$i"
	fi
	((i++))
done
