#!/usr/bin/env bash
# This script displays:
#	hours from 0 to 12
# 	minutes from 1 to 59

i=0
while [ $i -le 12 ]; do
	echo "Hour: $i"
	j=1
	while [ $j -lt 60 ]; do
		echo "$j"
		((j++))
	done
	((i++))
done
