#!/usr/bin/env bash
# This script shows the information about the "school" file

file=$(find . -name "school" -printf "%f")
if [ -n "$file" ]; then
	echo "$file file exists"
	exists=$(file "$file" | grep -q "directory")
	if [ -n "$exists" ]; then
		if [ -n "$(ls -1 "$file")" ]; then
			echo "$file file is not empty"
		else
			echo "$file file is empty"
		fi 
		echo "[Anything]" 1>&2
		exit 0
	else
		if [ -n "$(cat "$file")" ]; then
			echo "$file file is not empty"
		else
			echo "$file file is empty"
		fi
		echo "$file is a regular file"
	fi

else
	echo "school file does not exist"
fi
