#!/usr/bin/env bash
#
echo $$ > /var/run/myscript.pid
handle_signal() {
	case $1 in
        	SIGINT)
          		echo "SIGINT reçu (Ctrl+C). Arrêt du script."
			exit_code=2	
            	;;
        	SIGTERM)
            		echo "I hate the kill command"
	        	rm /var/run/myscript.pid
			exit_code=9    
			;;
        	SIGQUIT)
			rm /var/run/myscript.pid
			exit_code=3
            		;;
        	*)
            		;;
	esac
	exit "$exit_code"
}

# Trap signals
trap 'handle_signal SIGTERM' SIGTERM
trap 'hadle_signal SIGINT' SIGINT
trap 'handle_signal SIGQUIT' SIGQUIT

while true; do
	echo "To infinity and beyond"
done

